#!/bin/bash
#
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"

source "$PLUGIN_DIR/icon_map.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar display=all hidden=off position=top height=37 blur_radius=30 color=$BAR_COLOR topmost=window sticky=on

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="JetBrainsMono Nerd Font:Bold:13.0"
  label.font="JetBrainsMono Nerd Font:Bold:13.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Aerospace Workspace Indicators #####

sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_focus_change
sketchybar --add item aerospace left \
        --subscribe aerospace aerospace_workspace_change \
        --subscribe aerospace aerospace_focus_change \
        --set aerospace \
        label="󱂬" \
        click_script="aerospace reload-config" \
        script="$PLUGIN_DIR/aerospace_plugin"

##### Adding Left Items #####

sketchybar --add item chevron left \
  --set chevron icon= label.drawing=off \
  --add item front_app left \
  --set front_app \
  background.color=$ACCENT_COLOR \
  background.corner_radius=5 \
  background.height=25 \
  icon.color=$BAR_COLOR \
  icon.font="sketchybar-app-font:Regular:16.0" \
  label.color=$BAR_COLOR \
  script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

##### Adding Right Items #####

sketchybar --add item clock right \
  --set clock update_freq=10 icon= script="$PLUGIN_DIR/clock.sh" \
  --add item volume right \
  --set volume script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change \
  --add item battery right \
  --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change

sketchybar --add item disk right \
  --set disk update_freq=1 icon= script="$PLUGIN_DIR/disk.sh" padding_left=20 padding_right=20

sketchybar --add item net right \
  --set net update_freq=1 icon=󰇭 script="$PLUGIN_DIR/net.sh" padding_left=20 padding_right=20

sketchybar --add item mem right \
  --set mem update_freq=1 icon= script="$PLUGIN_DIR/mem.sh" padding_left=20 padding_right=20

sketchybar --add item cpu right \
  --set cpu update_freq=1 icon=􀧓 script="$PLUGIN_DIR/cpu.sh" padding_left=20 padding_right=20 icon.font="JetBrainsMono Nerd Font:Regular:14.0"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
